FROM golang:1.22.0-alpine AS builder

WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download

COPY ./sender/sender.go .

ENV CGO_ENABLED=0 GOOS=linux GOARCH=amd64
RUN go build -ldflags="-s -w" -o sender .
# RUN go build
# RUN CGO_ENABLED=0 GOOS=linux go build -o sender .
EXPOSE 3000

FROM scratch

COPY --from=builder ["/build/sender", "/"]

ENTRYPOINT ["/sender"]