FROM golang:1.16-alpine AS builder

WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download

COPY ./consumer/consumer.go .

ENV CGO_ENABLED=0 GOOS=linux GOARCH=amd64
RUN go build -ldflags="-s -w" -o receiver .
# RUN go build -o receiver .

FROM scratch

COPY --from=builder ["/build/receiver", "/"]

ENTRYPOINT ["/receiver"]